import "./globals.css";
import styles from "./layout.module.css";
import { Suspense } from "react";
import LoadingSpinner from "./components/LoadingSpinner";

export const metadata = {
  title: "Diary App",
  description: "Generated by create next app",
};
import StyledComponentsRegistry from "./lib/registry";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.layout}>
      <head>
        <title>Diary</title>
      </head>
      <body>
        <div className="pageWrapper">
          <StyledComponentsRegistry>
            <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
          </StyledComponentsRegistry>
        </div>
      </body>
    </html>
  );
}
