import "./globals.css";
import styles from "./layout.module.css";

export const metadata = {
  title: "Diary App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.layout}>
      <head>
        <title>Diary</title>
      </head>
      <body>
        <div className="pageWrapper">{children}</div>
      </body>
    </html>
  );
}
